# Most of this file content comes this great post blog: http://gediminasm.org/post/compile-php

FROM debian:wheezy

RUN apt-get update && apt-get install -y \
  build-essential \
  libcurl4-openssl-dev \
  libsqlite3-dev \
  libmysqlclient-dev \
  libreadline-dev \
  libzip-dev \
  libicu-dev \
  libpcre3-dev \
  libxslt1-dev \
  curl
